version: '4.31.1'


services:
  catalogdb:
    image: postgres


  catlogapi:
    image: ${DOCKER_REGISTRY-}catlogapi
    build:
      context: .
      dockerfile: Services/Catlog/CatlogApi/Dockerfile

volumes:
  postgres_catalog:

