version: '4.31.1'


services:
  catalogdb:
    image: postgres
  basketdb:
    image: postgres



  catlogapi:
    image: ${DOCKER_REGISTRY-}catlogapi
    build:
      context: .
      dockerfile: Services/Catlog/CatlogApi/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:

