version: '4.31.1'


services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  destributedcache:
    image: redis

  catlogapi:
    image: ${DOCKER_REGISTRY-}catlogapi
    build:
      context: .
      dockerfile: Services/Catlog/CatlogApi/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:


