version: '4.31.1'


services:
  catalogdb:
    image: postgres

  basketdb:
    image: postgres

  destributedcache:
    image: redis
  
  orderdb:
    image: mcr.microsoft.com/mssql/server

  catlogapi:
    image: ${DOCKER_REGISTRY-}catlogapi
    build:
      context: .
      dockerfile: Services/Catlog/CatlogApi/Dockerfile
  
  messagebroker:
    image: rabbitmq:management

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile

  discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:



