global using Basket.Api.Excrptions;
global using Basket.Api.Models;
global using BuildingBlocks.CQRS;
global using BuildingBlocks.Exception;
global using Carter;
global using FluentValidation;
global using Mapster;
global using Marten;
global using MediatR;